### ISSUE TITLE
Long URLs in forum posts cause layout to be too wide

### ISSUE THREAD

**Issue by KoenBrouwer** [pvdleek/somda2#7]
Link to topic: https://www.somda.nl/forum/15040/1/ontwikkelingen-icng/
Permalink to post (that doesn't work): https://www.somda.nl/forum/15040/p734549/ontwikkelingen-icng/

<img width="2277" alt="afbeelding" src="https://user-images.githubusercontent.com/3260168/106592347-b1846e00-654f-11eb-97a7-a9641c413b60.png">

<img width="2267" alt="afbeelding" src="https://user-images.githubusercontent.com/3260168/106592478-d842a480-654f-11eb-8676-6aa195ec417a.png">

**Comment by pvdleek** [comment]
Should be resolved now
